# Generated by Django 5.2.8 on 2025-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0001', max_length=10, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
                ('profesor', models.CharField(max_length=100)),
            ],
        ),
    ]
