# Generated by Django 5.2.7 on 2025-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.CharField(max_length=255)),
                ('Periodo', models.CharField(max_length=255)),
                ('Pendiente', models.BooleanField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
