# Generated by Django 5.2.8 on 2025-11-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evaluaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluaciones',
            old_name='Materia',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='evaluaciones',
            old_name='Pendiente',
            new_name='pendiente',
        ),
        migrations.RenameField(
            model_name='evaluaciones',
            old_name='Periodo',
            new_name='periodo',
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app.estudiante')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app.evaluaciones')),
            ],
            options={
                'unique_together': {('estudiante', 'evaluacion')},
            },
        ),
    ]
