# Generated by Django 5.2.8 on 2025-11-09 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_curso_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nome',
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='app.profesor'),
        ),
    ]
