# Generated by Django 5.2.7 on 2025-11-16 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loginestudiante_loginprofesor_estudiante_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contraseñas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.loginestudiante'),
        ),
        migrations.CreateModel(
            name='Estudiantes_pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(unique=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('contraseñas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.loginestudiante')),
            ],
        ),
    ]
