# Generated by Django 5.2.8 on 2025-11-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_materia_evaluaciones_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(unique=True),
        ),
    ]
