# Generated by Django 5.2 on 2025-11-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loginestudiante_loginprofesor_estudiante_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
