# Generated by Django 5.2.7 on 2025-11-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estudiante_contraseñas_estudiantes_pendientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes_pendientes',
            old_name='correo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='estudiantes_pendientes',
            name='contraseñas',
        ),
        migrations.AddField(
            model_name='estudiantes_pendientes',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='datos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.materia'),
        ),
    ]
