# Generated by Django 5.2.8 on 2025-11-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_estudiante_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
