# Generated by Django 5.2.7 on 2025-11-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estudiante_cedula'),
        ('app', '0005_rename_correo_estudiantes_pendientes_email_and_more'),
    ]

    operations = [
    ]
