# Generated by Django 5.2.8 on 2025-11-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(unique=True),
        ),
    ]
