# Generated by Django 5.2.7 on 2025-11-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20251117_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes_pendientes',
            name='cedula',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
