# Generated by Django 5.2.7 on 2025-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_estudiantes_pendientes_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiantes_pendientes',
            name='telefono',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
