# Generated by Django 5.2.7 on 2025-11-18 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_estudiante_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='materia',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='app.materia'),
        ),
    ]
