# Generated by Django 5.2.7 on 2025-11-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_estudiante_telefono_and_more'),  # <-- CAMBIA ESTO por el nombre exacto
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_nacimiento',
        ),
    ]
