# Generated by Django 5.2 on 2025-11-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_estudiante_telefono_and_more'),
        ('app', '0010_remove_profesor_fecha_nacimiento'),
    ]

    operations = [
    ]
