# Generated by Django 5.2.7 on 2025-11-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_profesor_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes_pendientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
