# Generated by Django 5.2 on 2025-11-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20251118_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes_pendientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
