# Generated by Django 5.2 on 2025-11-19 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_estudiantes_pendientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='materia',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='app.materia'),
        ),
    ]
